import { studioDestinations } from "../../lib/studio-navigation";

export default function GuidePage() {
  return <main className="mf-standalone">
    <a className="mf-back" href="/">← Back to MintForge</a>
    <span className="section-number">MINTFORGE GUIDE</span>
    <h1>Every tool.<br /><em>One studio.</em></h1>
    <nav className="guide-navigation" aria-label="MintForge tools">{studioDestinations.map((item) => <a className="mf-button" key={item.id} href={item.href}>{item.label} →</a>)}</nav>
    <section className="settings-card"><h2>Upload an entire collection</h2><p>Open Collection upload, then drop or select your artwork files. Each file becomes one artwork in the collection. You can add up to 10,000 artwork files plus 10,000 matching JSON files, with a 90 MiB limit per file.</p><p>Use Download CSV template to get the exact filenames. Put trait names in the header and trait values alongside each filename, then choose Import trait CSV. Metadata JSON files match artwork by filename: 1.json matches 1.png. Complete JSON objects, numeric traits and custom fields are retained; the main media link is replaced with the uploaded Irys URL. Duplicate or unmatched names are rejected. You can also edit traits on each item.</p><p>Continue through Collection, Mint settings, Revenue, Utility and Review. Configure the collection name, banner, social links, token standard, price, supply, reveal, royalties and collaborators. Your draft settings and upload checkpoints are saved in this browser. Reselect the same artwork and JSON files after reloading to resume completed batches. Clearing browser data removes these checkpoints. Review the itemized Irys storage quote and network fees before approving payment. Irys URLs are separate from IPFS CIDs; this flow does not create an IPFS copy.</p></section>
    <section className="settings-card"><h2>ERC-404 minting</h2><p>Select ERC-404 in Collection for an experimental fixed-supply hybrid of fungible tokens and NFTs. One whole token links to one NFT; fractional transfers can bank and later restore NFT IDs. MintForge can trade and stake whole linked NFTs. Use the full encoded token ID for manual lookup. Indexer and wallet support varies.</p></section>
    <section className="settings-card"><h2>Dashboard</h2><p>Resume your saved draft or connect the creator wallet to see deployed collections. Mint progress and proceeds come from the contracts. Holder counts come from the network’s explorer and may take time to update. A dash means data is unavailable.</p><p>Use collection controls to withdraw proceeds, change price, pause minting, reveal artwork or edit metadata. Manage staking pool opens the staking workspace. A collection whose ownership was transferred to you can be loaded by address.</p></section>
    <section className="settings-card"><h2>Marketplace</h2><p>Browse listings, inspect artwork and traits, buy at a fixed price or submit an offer. List an NFT opens your wallet gallery and also supports entering a contract and token ID manually.</p><p>Choose Fixed price or Accept offers only. My listings &amp; offers contains seller listings and offers you made. Sellers can update prices, accept funded offers or cancel a listing. Cancel an unaccepted offer to credit a refund, then use Withdraw to collect your balance.</p></section>
    <section className="settings-card"><h2>Viewing and staking</h2><p>View NFT supports wallet browsing and lookup by contract, token ID or metadata URI. Use Stake NFTs to select a funded pool, stake eligible NFTs, manage positions and withdraw rewards. Creators can create and fund reward pools in the same workspace.</p></section>
    <section className="settings-card"><h2>Network activation</h2><p>You can prepare your collection and explore every workspace before activation. Publishing, minting, sales and staking need configured contracts on the selected network. Uploads also need the site’s storage service. Your wallet reviews and signs each transaction.</p><a className="mf-button" href="/setup">Open launch setup →</a></section>
  </main>;
}
